name: CI/CD_BRANCH

on:
  pull_request:
    branches:
      - '**'

jobs:
  check_branch_convention:
    name: Conventional Branch Name
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z])+\/([\dA-Za-z_-])+\/([\dA-Za-z_-])+\/([\dA-Za-z_-])+'
          allowed_prefixes: 'feature,stable,fix,chore,docs,feat,build,ci,test,refactor,perf'
          ignore: main,stage,develop
          min_length: 4
          max_length: 150
