name: CI/CD_PR

on:
  pull_request:
    branches:
      - '**'

permissions: read-all

jobs:
  semantic_pull_request:
    runs-on: ubuntu-latest
    name: Conventional Pull Request
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: false

  check_all_commits_message:
    name: Conventional Commits Message
    runs-on: ubuntu-latest
    steps:
      - uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(?:build|docs|doc|refactor|test|fix|perf|chore|feat|ci)(?:\(.+\))?:\s[a-zA-Z]{1,2}.+'
          error: 'The commit message must follow the commit messages guidelines'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
